name: Playwright Python Automation CI

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps

    - name: Run Pytest tests
      run: |
        pytest --alluredir=allure-results

    # generate and upload Allure report

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report

    - name: Upload Allure HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report
